Updated Action to use Nuitka 1.3.8 and added options for show-scons and building with MinGW64
Nuitka/Nuitka-Action pull request #11
Opened 2023-01-26 15:07 UTC by WhosMyName

2023-01-26 17:28 UTC, kayhayen commented on action.yml
> +  windows-mingw-build:
I would love for us to keep using the option names, in this case `ming64` then.

2023-01-26 17:30 UTC, kayhayen commented
@jimkring outside of the option name for `--mingw64`, I do not have complaints, I suggest you merge this one?

One thing I noticed however, is that the default Nuitka version is not just a branch name, like `main`, can we do it like that, I don't think it's good to update this for every hotfix or Nuitka.

2023-01-26 17:31 UTC, kayhayen requested changes
If you change the Yaml option name to match the command line name, it will be perfect. We intend to actually read the command line options from the Yaml file in the future, then it would be great if they already matched as much as possible.

2023-01-26 20:19 UTC, WhosMyName commented
change implemented in bc4a461
ready to merge

2023-01-27 08:38 UTC, merged

2023-01-27 08:39 UTC, kayhayen commented
Merged this. After looking at it, I am somewhat more in doubt, if Nuitka options can be done automatically from the Yaml configuration. It seems we might need some sort of code generator to achieve that. Not sure if it is worth it.